settings:
  use-levels: true
  max-items-per-day: 9
  discount-chance: 0.25
  discount-min: 0.10
  discount-max: 0.50
  schedule-mode: minecraft-night
  timezone: UTC
  open-hours:
    - '20:00-23:59'
    - '00:00-02:00'
items:
  diamond_sword:
    display-name: '<gradient:#00BFFF:#1E90FF>&lDiamond Sword</gradient>'
    material: DIAMOND_SWORD
    price: 1000.0
    exp-price: 15
    stock: 3
    lore:
      - '&7A powerful weapon'
      - '&7forged from diamonds'
    commands:
      - 'give {player} diamond_sword 1'
  god_apple:
    display-name: '<gradient:#FFD700:#FFA500>&lEnchanted Golden Apple</gradient>'
    material: ENCHANTED_GOLDEN_APPLE
    price: 2500.0
    exp-price: 30
    stock: 1
    lore:
      - '&7The ultimate healing item'
      - '&7Grants incredible powers'
    commands:
      - 'give {player} enchanted_golden_apple 1'
  netherite_armor:
    display-name: '<gradient:#4B0082:#8A2BE2>&lNetherite Armor Set</gradient>'
    material: NETHERITE_CHESTPLATE
    price: 5000.0
    exp-price: 50
    stock: 1
    lore:
      - '&7Complete netherite armor set'
      - '&7Maximum protection'
    commands:
      - 'give {player} netherite_helmet 1'
      - 'give {player} netherite_chestplate 1'
      - 'give {player} netherite_leggings 1'
      - 'give {player} netherite_boots 1'
  elytra:
    display-name: '<gradient:#87CEEB:#00CED1>&lElytra Wings</gradient>'
    material: ELYTRA
    price: 3500.0
    exp-price: 40
    stock: 1
    lore:
      - '&7Fly through the skies'
      - '&7The ultimate transportation'
    commands:
      - 'give {player} elytra 1'