name: Black-Market
version: '1.5'
main: com.Lino.blackMarket.BlackMarket
author: Lino
api-version: '1.21'
softdepend: [Vault]
commands:
  blackmarket:
    description: Opens the Black Market GUI or shows help
    usage: /<command> [help|reload|forceopen|edit|forcenew]
    aliases: [bm, blackm, market]
    permission: blackmarket.use
permissions:
  blackmarket.use:
    description: Allows use of the black market
    default: true
  blackmarket.admin:
    description: Admin permissions for black market
    default: op